name: Tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install development dependencies
        run: pip install -r requirements_dev.txt
      - name: Install package
        run: pip install .
      - name: test with poetry
        run: |
          poetry run mypy src/
          poetry run flake8 src/
          poetry run pytest
    
