name: Tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.0.0
      - name: Install dependencies
        run: poetry install --no-root
      - name: test with poetry
        run: |
          poetry run mypy src/
          poetry run flake8 src/
          poetry run pytest
    
